### ISSUE TITLE
SageMath 9.5 for Windows

### ISSUE THREAD

**Issue by ghost** [embray/sage-windows#20] opened 2022-04-13 14:05 UTC
Hi !

SageMath 9.2 is working fine, but with SageMath 9.3 I have the same issue that`s described here: https://github.com/sagemath/sage-windows/issues/61 and https://ask.sagemath.org/question/61753/sage-crashing-on-notebook-startup/ on Windows 10

Building Sage from source is a bit difficult for me. But I can`t find installer binaries of the newest SageMath 9.5 for Windows.

**Comment by embray** [comment] 2022-04-15 10:17
I'm not even totally sure if that issue is fixed on 9.5.  The problem is not really specific to any particular Sage version--it's a problem with building NumPy in a way that's platform-independent, so the reason some people have this problem is that the NumPy build is not compatible with the CPUs on their systems.

It's not a problem particular to the Windows version either--it just happens that the existing Windows releases were built on my machine with my CPU.  If you build it from source (which many Linux users do) the problem won't exist.  I have also heard that Sage works pretty well these days on Windows Subsystem for Linux (which is basically just a glorified Linux VM).

**Comment by embray** [comment] 2022-04-15 10:20
Also please open issues on the official repository at https://github.com/sagemath/sage-windows

This is my personal fork which I think has been obsolete for some time.  I'll be shutting off new issues on this repo to avoid confusion.

**Closed as completed by embray** 2022-04-15 10:20 UTC
